introduce cmake presets and separate test to its own workflow job  (#47)
* trying a seperate windows workflow with my own cmake actions

* test xcode generator for macos runner

* test cmake presets

* Update CI.yaml

* update cmakepresets.json

* change build preset to Release

* fix target mistake in preset

* remove verbose build output

* test macos preset running AU tests with PLuginval

* terminate AudioComponentRegistrar from cmake

* creating test step github actions

* update ci.yaml

* update ci.yaml again

* test change permissions

* update ci.yaml

* change path of au plugins copy

* update ci.yaml file

* update workflow

* remove unused files for ci

* remove unused workflow action

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -30,23 +30,27 @@ jobs:
           sudo apt-get update
           sudo apt install doxygen graphviz libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
 
-      - name: Configure
-        run: cmake -DCMAKE_BUILD_TYPE=Release -DJUCE_COPY_PLUGIN_AFTER_BUILD=ON -B build -S .
+      - name: Set CMake default generator
+        if: matrix.os == 'macos-latest'
+        run: echo "CMAKE_GENERATOR=Xcode" >> $GITHUB_ENV
 
       - name: Build
-        run: cmake --build build --config Release -j 4
-
-      - name: Kill AudioComponentRegistrar
-        if: matrix.os == 'macos-latest'
-        run: |
-          pgrep -x AudioComponentRegistrar >/dev/null && killall -9 AudioComponentRegistrar; echo "killed AudioComponentRegistrar" || echo "AudioComponentRegistrar Process not found"
-
-      - name: Tests
-        run: ctest --test-dir build -C Release --output-on-failure
+        run: cmake --workflow --preset Release
 
       - name: Generate documentation
         if: matrix.os == 'ubuntu-latest'
-        run: cmake --build build --target docs --config Release -j 4
+        run: cmake --build --preset Docs
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: build-${{matrix.os}}
+          path: |
+            CMakePresets.json
+            build/**
+            !build/build
+            !**/*_SharedCode.a
+            !build/_deps/juce-*/
 
       - name: Upload build artifact
         if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
@@ -55,9 +59,38 @@ jobs:
           name: doxygen-docs
           path: build/docs/html
 
+  test:
+    name: Test
+    needs: build
+    runs-on: ${{matrix.os}}
+    strategy:
+      matrix:
+        os: [windows-latest, macos-latest, ubuntu-latest]
+
+    steps:
+      - name: Download Build Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-${{matrix.os}}
+
+      - name: Change permissions
+        if: matrix.os != 'windows-latest'
+        run: chmod -R +x build/_deps/pluginval-src/
+
+      - name: Register AU plugins
+        if: matrix.os == 'macos-latest'
+        run: |
+          mkdir -p ~/Library/Audio/Plug-Ins/Components
+          find build -name "*.component" -exec cp -r {} ~/Library/Audio/Plug-Ins/Components/ \;
+          pgrep -x AudioComponentRegistrar >/dev/null && killall -9 AudioComponentRegistrar; echo "killed AudioComponentRegistrar" || echo "AudioComponentRegistrar Process not found"
+        shell: bash
+
+      - name: Run Tests
+        run: ctest --preset Release
+
   deploy:
     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-    needs: build
+    needs: test
     runs-on: ubuntu-latest
 
     steps:
